name: Run Tests for Module Header Files

on:
  workflow_dispatch:
    inputs:
      modules:
        type: string
        required: false
        description: Specify the modules you want to run tests for seperated by semicolons. Available is 'can'. Example':' 'can' (case sensitive).

  pull_request:
    branches:
      - integrationtests-for-ls-bus-header
      - main
    paths:
      - 'headers/**'
      - 'tests/**'

jobs:
  test-header-files:
    name: Test module header files
    runs-on: ubuntu-latest

    steps:
    - name: Install googletest
      run: |
        set -e
        sudo apt-get install libgtest-dev
    - uses: actions/checkout@v1

    - name: Checkout fmi-standard Repository
      run: ls -R
    - uses: actions/checkout@v4
      with:
        repository: modelica/fmi-standard
        ref: refs/heads/main

    - name: Copy PlatformTypes.h
      run: |
        cp /home/runner/work/fmi-ls-bus/fmi-ls-bus/modelica/fmi-standard/headers/fmi3PlatformTypes.h $GITHUB_WORKSPACE/headers

    - name: Configure
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DMODULE_LIST="${{inputs.modules}}" ..
      working-directory: ./tests

    - name: Build test project
      run: |
        cmake --build .
      working-directory: ./tests/build

    - name: Execute tests
      run: |
        ctest
      working-directory: ./tests/build
