name: Run Tests for Module Header Files

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  check-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get changed header files
      id: changed-header-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          **.h
    - name: Check for header files
      if: steps.changed-header-files.outputs.any_changed == 'true'
      run: $printf "Header Files vorhanden"
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest manually
      run: set -e && sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: ./headers/tests
    - name: Build test project
      run: cd build && make
      working-directory: ./headers/tests
    - name: Execute tests
      run: /home/runner/work/fmi-ls-bus/fmi-ls-bus/headers/tests/build/test/fmi_3_ls_bus_header_test.test
